const GET_MOVIES = 'GET_MOVIES';
const GET_GENRES = 'GET_GENRES';
const GET_MOVIE_INFO = 'GET_MOVIE_INFO';
const SET_DARK_THEME = 'SET_DARK_THEME';
const SET_LIGHT_THEME = 'SET_LIGHT_THEME';

export {GET_MOVIES, GET_GENRES, GET_MOVIE_INFO, SET_DARK_THEME, SET_LIGHT_THEME}
