const GET_MOVIES = 'GET_MOVIES';
const GET_GENRES = 'GET_GENRES';
const GET_MOVIE_INFO = 'GET_MOVIE_INFO';
const SET_DARK_THEME = 'SET_DARK_THEME';
const SET_LIGHT_THEME = 'SET_LIGHT_THEME';
const SET_CURRENT_PAGE = 'SET_CURRENT_PAGE';
const GET_MOVIES_BY_GENRE = 'GET_MOVIES_BY_GENRE';
const SET_MOVIES_BY_GENRE = 'SET_MOVIES_BY_GENRE';

export {
    GET_MOVIES,
    GET_GENRES,
    GET_MOVIE_INFO,
    SET_DARK_THEME,
    SET_LIGHT_THEME,
    SET_CURRENT_PAGE,
    GET_MOVIES_BY_GENRE,
    SET_MOVIES_BY_GENRE
}
